#!/usr/bin/env bash

## launch kitty with alt config

CONFIG="$HOME/.config/hypr/kitty/kitty.conf"

if [ "$1" == "-f" ]; then
	kitty --app-id='foot-float' --config="$CONFIG"
elif [ "$1" == "-F" ]; then
	kitty --fullscreen --app-id='foot-full' --font="Iosevka Nerd Font:size=14" --override=pad=35x35 --config="$CONFIG"
elif [ "$1" == "-s" ]; then
	kitty --app-id='foot-float' --config="$CONFIG" \
	--window-size-pixels=$(slurp -b 1E1E2ECC -c 89B4FAff -s 89B4FA0D -w 2 -f "%wx%h")
else
	foot --config="$CONFIG"
fi